// <auto-generated />
using CalculatorAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalculatorAPI.Migrations
{
    [DbContext(typeof(CalculationDbContext))]
    [Migration("20260611140508_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.20");

            modelBuilder.Entity("KotelUtilizatorLibrary.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KotelUtilizatorLibrary.Models.Variant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Variants");
                });

            modelBuilder.Entity("KotelUtilizatorLibrary.Models.VariantUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Co2")
                        .HasColumnType("REAL");

                    b.Property<double>("Cross_sectional_area_for_passage_of_combustion_products_1")
                        .HasColumnType("REAL");

                    b.Property<double>("Cross_sectional_area_for_passage_of_combustion_products_2")
                        .HasColumnType("REAL");

                    b.Property<double>("Cross_sectional_area_for_passage_of_combustion_products_3")
                        .HasColumnType("REAL");

                    b.Property<double>("Cross_sectional_area_for_passage_of_combustion_products_4")
                        .HasColumnType("REAL");

                    b.Property<double>("Estimated_heating_surface_area_1")
                        .HasColumnType("REAL");

                    b.Property<double>("Estimated_heating_surface_area_2")
                        .HasColumnType("REAL");

                    b.Property<double>("Estimated_heating_surface_area_3")
                        .HasColumnType("REAL");

                    b.Property<double>("Estimated_heating_surface_area_4")
                        .HasColumnType("REAL");

                    b.Property<double>("Gaz_used")
                        .HasColumnType("REAL");

                    b.Property<double>("H2o")
                        .HasColumnType("REAL");

                    b.Property<double>("Heat_preservation_coefficient")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitudinal_pitch_of_pipes_1")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitudinal_pitch_of_pipes_2")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitudinal_pitch_of_pipes_3")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitudinal_pitch_of_pipes_4")
                        .HasColumnType("REAL");

                    b.Property<double>("N2")
                        .HasColumnType("REAL");

                    b.Property<double>("Number_of_pipe_rows_1")
                        .HasColumnType("REAL");

                    b.Property<double>("Number_of_pipe_rows_2")
                        .HasColumnType("REAL");

                    b.Property<double>("Number_of_pipe_rows_3")
                        .HasColumnType("REAL");

                    b.Property<double>("Number_of_pipe_rows_4")
                        .HasColumnType("REAL");

                    b.Property<double>("O2")
                        .HasColumnType("REAL");

                    b.Property<double>("Pipe_diametr_1")
                        .HasColumnType("REAL");

                    b.Property<double>("Pipe_diametr_2")
                        .HasColumnType("REAL");

                    b.Property<double>("Pipe_diametr_3")
                        .HasColumnType("REAL");

                    b.Property<double>("Pipe_diametr_4")
                        .HasColumnType("REAL");

                    b.Property<double>("Popravka_na_chair_radov_pipes_1")
                        .HasColumnType("REAL");

                    b.Property<double>("Popravka_na_chair_radov_pipes_2")
                        .HasColumnType("REAL");

                    b.Property<double>("Popravka_na_chair_radov_pipes_3")
                        .HasColumnType("REAL");

                    b.Property<double>("Popravka_na_chair_radov_pipes_4")
                        .HasColumnType("REAL");

                    b.Property<double>("Presure_putten_par")
                        .HasColumnType("REAL");

                    b.Property<double>("Proportion_of_intake_air")
                        .HasColumnType("REAL");

                    b.Property<double>("Purge_n")
                        .HasColumnType("REAL");

                    b.Property<double>("Temperature_arrive_smoke")
                        .HasColumnType("REAL");

                    b.Property<double>("Temperature_eaten_water")
                        .HasColumnType("REAL");

                    b.Property<double>("Temperature_of_incoming_gases_1")
                        .HasColumnType("REAL");

                    b.Property<double>("Temperature_of_incoming_gases_2")
                        .HasColumnType("REAL");

                    b.Property<double>("Temperature_of_incoming_gases_3")
                        .HasColumnType("REAL");

                    b.Property<double>("Temperature_of_incoming_gases_4")
                        .HasColumnType("REAL");

                    b.Property<double>("Temperature_of_outcoming_gases_1")
                        .HasColumnType("REAL");

                    b.Property<double>("Temperature_of_outcoming_gases_2")
                        .HasColumnType("REAL");

                    b.Property<double>("Temperature_of_outcoming_gases_3")
                        .HasColumnType("REAL");

                    b.Property<double>("Temperature_of_outcoming_gases_4")
                        .HasColumnType("REAL");

                    b.Property<double>("Temperature_of_the_the_heated_medium_at_The_inlet_1")
                        .HasColumnType("REAL");

                    b.Property<double>("Temperature_of_the_the_heated_medium_at_The_inlet_2")
                        .HasColumnType("REAL");

                    b.Property<double>("Temperature_of_the_the_heated_medium_at_The_inlet_3")
                        .HasColumnType("REAL");

                    b.Property<double>("Temperature_of_the_the_heated_medium_at_The_inlet_4")
                        .HasColumnType("REAL");

                    b.Property<double>("Temperature_of_the_the_heated_medium_at_The_outlet_1")
                        .HasColumnType("REAL");

                    b.Property<double>("Temperature_of_the_the_heated_medium_at_The_outlet_2")
                        .HasColumnType("REAL");

                    b.Property<double>("Temperature_of_the_the_heated_medium_at_The_outlet_3")
                        .HasColumnType("REAL");

                    b.Property<double>("Temperature_of_the_the_heated_medium_at_The_outlet_4")
                        .HasColumnType("REAL");

                    b.Property<double>("The_degree_of_blackness_of_the_walls_of_the_tube_package")
                        .HasColumnType("REAL");

                    b.Property<double>("The_emission_coefficient_of_a_completely_black_body")
                        .HasColumnType("REAL");

                    b.Property<double>("Thermal_resistance_of_deposits_on_pipes")
                        .HasColumnType("REAL");

                    b.Property<double>("Transverse_pitch_of_pipe_1")
                        .HasColumnType("REAL");

                    b.Property<double>("Transverse_pitch_of_pipe_2")
                        .HasColumnType("REAL");

                    b.Property<double>("Transverse_pitch_of_pipe_3")
                        .HasColumnType("REAL");

                    b.Property<double>("Transverse_pitch_of_pipe_4")
                        .HasColumnType("REAL");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VariantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VariantId");

                    b.ToTable("VariantUsers");
                });

            modelBuilder.Entity("KotelUtilizatorLibrary.Models.Variant", b =>
                {
                    b.HasOne("KotelUtilizatorLibrary.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KotelUtilizatorLibrary.Models.VariantUser", b =>
                {
                    b.HasOne("KotelUtilizatorLibrary.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KotelUtilizatorLibrary.Models.Variant", "Variant")
                        .WithMany()
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Variant");
                });
#pragma warning restore 612, 618
        }
    }
}
